name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --workspace -- -D warnings

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Test
        run: cargo test --all-targets --workspace
        env:
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
          JAVA_HOME: ${{ matrix.os == 'macos-latest' && '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home' || '' }}
