name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --workspace -- -D warnings

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Test
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "Running tests on macOS, excluding hdfs-sys..."
            cargo test --all-targets --workspace --exclude hdfs-sys
          else
            echo "Running full test suite on ${{ matrix.os }}..."
            cargo test --all-targets --workspace
          fi
        env:
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
