name: Test Behavior
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup MinIO
        uses: ./.github/services/minio

      - name: Wait for MinIO readiness
        shell: bash
        run: |
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:9000/minio/health/ready >/dev/null; then
              echo "MinIO ready"; exit 0; fi
            sleep 1
          done
          echo "MinIO not ready" >&2; exit 1

      - name: Run Behavior Tests
        run: cargo test --test behavior --quiet
        env:
          RUST_LOG: info

      - name: Cleanup
        if: always()
        shell: bash
        working-directory: .github/services/minio
        run: docker compose down
